# Generated by Django 6.0.2 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyplan",
            name="focus_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
