# Generated by Django 6.0.2 on 2026-03-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planning", "0002_dailyplan_focus_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recurring_plans", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="dailyplan",
            name="recurring_source",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="generated_plans", to="planning.recurringplan"),
        ),
    ]
