# Generated by Django 6.0.2 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_recurringplan_dailyplan_recurring_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringplan",
            name="repeat_days",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
